# Pipeline used to delete a Power Platform environment and its associated Power Platform service connection

# Pipeline triggered manually
trigger: none

parameters:
#  EnvironmentName: Name of the Power Platform environment to delete
- name: EnvironmentNameParameter
  displayName: Power Platform environment Name
  type: string
#  PowerPlatformServiceEndpointName: Name of the Power Platform service connection to delete
- name: PowerPlatformServiceEndpointNameParameter
  displayName: Power Platform service connection Name
  type: string

variables:
  # Variable group with the following variables:
  #   AzureDevOpsOrganizationURL: URL of the considered Azure DevOps organization (ex: https://dev.azure.com/<organization>/)
  #   PatToken: Personal Access Token is full permissions for the creation of the Power Platform service connection
  - group: power-platform-environment-management-variable-group

  - name: EnvironmentName
    value: ${{ parameters.EnvironmentNameParameter }}

  - name: PowerPlatformServiceEndpointName
    value: ${{ parameters.PowerPlatformServiceEndpointNameParameter }}

stages:
# Stage for the deletion of the Power Platform environment
- stage: 'PowerPlatformEnvironmentDeletion'
  displayName: 'Power Platform Environment Deletion'
  jobs:
    - job: 'PowerPlatformEnvironmentDeletion'
      displayName: 'PowerPlatformEnvironmentDeletion Job'
      pool:
        vmImage: 'windows-latest'

      steps:
      # Installation of the Power Platform Build Tools extension
      - task: PowerPlatformToolInstaller@0
        displayName: 'Install Power Platform Build Tools'
        inputs:
          DefaultVersion: true
      
      # Deletion of the Power Platform Environment
      - task: PowerPlatformDeleteEnvironment@0
        displayName: 'Delete Power Platform environment'
        inputs:
          authenticationType: 'PowerPlatformSPN'
          PowerPlatformSPN: '$(PowerPlatformServiceEndpointName)'

# Stage for the deletion of the associated service endpoint
- stage: 'ServiceEndpointDeletion'
  displayName: 'Service Endpoint Deletion'
  dependsOn: PowerPlatformEnvironmentDeletion
  condition: succeeded()
  jobs:
    - job: 'ServiceEndpointDeletion'
      displayName: 'ServiceEndpointDeletion Job'
      pool:
        vmImage: 'windows-latest'

      steps:
      # Call to the pipeline template for the deletion of a Power Platform service endpoint
      - template: ../Templates/delete-powerplatform-service-endpoint-template.yml