# Pipeline used to delete a service endpoint

# Variables to create
# EnvironmentName - String - Not secret - Let user override
# AzureDevOpsOrganizationURL - String - Secret - Do not let user override
# PatToken - String - Secret - Do not let user override

trigger: none

variables:
  # Replace " " by "-" in EnvironmentName variable
  customEnvironmentName: $[ replace(variables['EnvironmentName'], ' ', '-') ]

pool:
  vmImage: 'windows-2019'

steps:
# Delete a Power Platform service endpoint based the Environment name associated
- powershell: |
    $org = '$(AzureDevOpsOrganizationURL)'
    $env:AZURE_DEVOPS_EXT_PAT = '$(PatToken)'

    $projectServiceEndpoints = az devops service-endpoint list --organization $org --project $(System.TeamProjectId)

    $projectServiceEndpointsAsJSON = $projectServiceEndpoints | ConvertFrom-Json

    $targetedprojectServiceEndpoint = $projectServiceEndpointsAsJSON | where { $_.name -eq "$(customEnvironmentName)" }

    $serviceEndpointId = $targetedprojectServiceEndpoint.id

    az devops service-endpoint delete --id $serviceEndpointId --yes